### ISSUE TITLE
Test with the latest version of WSAL free and WSAL premium

### ISSUE THREAD

**Issue by robert81** [wpwhitesecurity/wsal-woocommerce#191]
Before the go ahead and release we should test the plugin with the latest releases of both the Free and Premium plugin to avoid any disappointments.

**Comment by DannyWPWS** [comment]
Reference - this is the error originally seen, which iv been unable to replicate 

````
Fatal error: Uncaught Error: Object of class WSAL_Sensors_WooCommerce could not be converted to string in /mnt/volume_ams3_01/www/robert.wpwhitesecurity.net/ppmwp/wp-content/plugins/wp-activity-log-for-woocommerce/wp-security-audit-log/custom-sensors/WSAL_Sensors_WooCommerce.php:2115 Stack trace: #0 /mnt/volume_ams3_01/www/robert.wpwhitesecurity.net/ppmwp/wp-includes/class-wp-hook.php(307): WSAL_Sensors_WooCommerce->settings_updated() #1 /mnt/volume_ams3_01/www/robert.wpwhitesecurity.net/ppmwp/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters() #2 /mnt/volume_ams3_01/www/robert.wpwhitesecurity.net/ppmwp/wp-includes/plugin.php(474): WP_Hook->do_action() #3 /mnt/volume_ams3_01/www/robert.wpwhitesecurity.net/ppmwp/wp-includes/option.php(538): do_action() #4 /mnt/volume_ams3_01/www/robert.wpwhitesecurity.net/ppmwp/wp-content/plugins/woocommerce/includes/admin/class-wc-admin-settings.php(901): update_option() #5 /mnt/volume_ams3_01/www/robert.wpwhitesecurity.net/ppmwp/wp-content/plugins/woocommerce/includes/admin/sett in /mnt/volume_ams3_01/www/robert.wpwhitesecurity.net/ppmwp/wp-content/plugins/wp-activity-log-for-woocommerce/wp-security-audit-log/custom-sensors/WSAL_Sensors_WooCommerce.php on line 2115
````

But, there is a typo at line 2115 which cant be just coincidental - PR incoming
