### ISSUE TITLE
Fatal error upon placing order

### ISSUE THREAD

**Issue by robert81** [wpwhitesecurity/wsal-woocommerce#243]
While testing the latest version of this extension with WSAL 4.4.3, when I place an order I get an "internal server error" on the website and the below in the debug log file.

**Notes:** 
1. This works fine with WSAL 4.4.2.2.
2. This can be reproduced on https://site1.robert.wpws.org/

[16-Nov-2022 19:15:50 UTC] PHP Deprecated:  Function get_global_boolean_setting is <strong>deprecated</strong> since version 4.4.3! Use \WSAL\Helpers\Settings_Helper::get_boolean_option_value() instead. in /var/www/robert.wpws.org/site1/wp-includes/functions.php on line 5383
[16-Nov-2022 19:15:50 UTC] PHP Fatal error:  Uncaught Error: Call to a member function GetMetaArray() on array in /var/www/robert.wpws.org/site1/wp-content/plugins/wp-activity-log-for-woocommerce/wp-security-audit-log/custom-sensors/WSAL_Sensors_WooCommerce_Public.php:366
Stack trace:
#0 /var/www/robert.wpws.org/site1/wp-includes/class-wp-hook.php(308): WSAL_Sensors_WooCommerce_Public->product_stock_changed()
#1 /var/www/robert.wpws.org/site1/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#2 /var/www/robert.wpws.org/site1/wp-includes/plugin.php(517): WP_Hook->do_action()
#3 /var/www/robert.wpws.org/site1/wp-content/plugins/woocommerce/includes/wc-stock-functions.php(63): do_action()
#4 /var/www/robert.wpws.org/site1/wp-content/plugins/woocommerce/includes/wc-stock-functions.php(189): wc_update_product_stock()
#5 /var/www/robert.wpws.org/site1/wp-content/plugins/woocommerce/includes/wc-stock-functions.php(107): wc_reduce_stock_levels()
#6 /var/www/robert.wpws.org/site1/wp-includes/class-wp-hook.php(310): wc_maybe_reduce_stock_levels()
#7 /v in /var/www/robert.wpws.org/site1/wp-content/plugins/wp-activity-log-for-woocommerce/wp-security-audit-log/custom-sensors/WSAL_Sensors_WooCommerce_Public.php on line 366

**Comment by DannyWPWS** [comment]
FYI this part

[16-Nov-2022 19:15:50 UTC] PHP Deprecated: Function get_global_boolean_setting is deprecated since version 4.4.3! Use \WSAL\Helpers\Settings_Helper::get_boolean_option_value() instead. in /var/www/robert.wpws.org/site1/wp-includes/functions.php on line 5383

Is unrelated to this extension (the function simply does not exist) so will find the culpit today
