### ISSUE TITLE
PHP Fatal error thrown when manipulating order

### ISSUE THREAD

**Issue by jwjsystem** [wpwhitesecurity/wsal-woocommerce#252]
I got this in the debug log just after changing the status of an order, and it's date.  Basically, along with the below order, you should be able to reproduce it, simply change it's status to anything else.

 (leaving it here for testing purposes for a while)

https://site4.lucian.wpws.org/wp-admin/post.php?post=25&action=edit

```
[21-Mar-2023 12:42:03 UTC] PHP Fatal error:  Uncaught Exception: Invalid order. in /var/www/lucian.wpws.org/site4/wp-content/plugins/woocommerce/includes/data-stores/abstract-wc-order-data-store-cpt.php:120
Stack trace:
#0 /var/www/lucian.wpws.org/site4/wp-content/plugins/woocommerce/includes/class-wc-data-store.php(159): Abstract_WC_Order_Data_Store_CPT->read()
#1 /var/www/lucian.wpws.org/site4/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-order.php(128): WC_Data_Store->read()
#2 /var/www/lucian.wpws.org/site4/wp-content/plugins/wp-activity-log-for-woocommerce/includes/wsal-functions.php(239): WC_Abstract_Order->__construct()
#3 /var/www/lucian.wpws.org/site4/wp-includes/class-wp-hook.php(308): wsal_woocommerce_extension_add_custom_meta_format()
#4 /var/www/lucian.wpws.org/site4/wp-includes/plugin.php(205): WP_Hook->apply_filters()
#5 /var/www/lucian.wpws.org/site4/wp-content/plugins/wp-security-audit-log-premium/classes/AlertFormatter.php(261): apply_filters()
#6 /var/www/lucian.wpws.org/site4/wp-content/plugins/wp-security-audit-log-p in /var/www/lucian.wpws.org/site4/wp-content/plugins/woocommerce/includes/data-stores/abstract-wc-order-data-store-cpt.php on line 120
```

**Comment by sdobreff** [comment]
Unreproducable

**Comment by jwjsystem** [comment]
No longer reproducing - closing.  Might have been a one time thing, I'll reopen it if I managed to reproduce while re-testing everything now.
