### ISSUE TITLE
#12440 Fatal error when creating delivery - WSAL + WooCommerce + Partial Delivery

### ISSUE THREAD

**Issue by jwjsystem** [wpwhitesecurity/wsal-woocommerce#257]
**Steps in reproducing the problem**

1) You need the following plugins installed and activated:
- WooCommerce
- Partial Delivery for WooCommerce
 https://krokedil.com/product/partial-delivery-for-woocommerce/.
[partial-delivery-for-woocommerce-7-b29265dd17e1d8ef90ab20f06bfd621c.zip](https://github.com/wpwhitesecurity/wp-security-audit-log-premium/files/11176556/partial-delivery-for-woocommerce-7-b29265dd17e1d8ef90ab20f06bfd621c.zip)

- WP Activity Log
- WP Activity Log for WooCommerce

2) Have an order that have order status set to processing or on-hold
3) Create a delivery from that order
4) You can then see that the loading screen continue to load and can see in the network tab that you got a 500 error
5) You can see the fatal error shown below in the fatal error log

**Fatal error reported** 

```
2023-03-28T12:42:39+00:00 CRITICAL Uncaught TypeError: parse_str(): Argument #1 ($string) must be of type string, array given in /home/luwuriveba1620/web/pd-ntnu-test.instawp.xyz/public_html/wp-content/plugins/wp-activity-log-for-woocommerce/wp-security-audit-log/custom-sensors/WSAL_Sensors_WooCommerce.php:3555
Stack trace:
#0 /home/luwuriveba1620/web/pd-ntnu-test.instawp.xyz/public_html/wp-content/plugins/wp-activity-log-for-woocommerce/wp-security-audit-log/custom-sensors/WSAL_Sensors_WooCommerce.php(3555): parse_str()
#1 /home/luwuriveba1620/web/pd-ntnu-test.instawp.xyz/public_html/wp-content/plugins/wp-activity-log-for-woocommerce/wp-security-audit-log/custom-sensors/WSAL_Sensors_WooCommerce.php(3711): WSAL_Sensors_WooCommerce->event_order_items_quantity_changed()
#2 /home/luwuriveba1620/web/pd-ntnu-test.instawp.xyz/public_html/wp-content/plugins/wp-activity-log-for-woocommerce/wp-security-audit-log/custom-sensors/WSAL_Sensors_WooCommerce.php(570): WSAL_Sensors_WooCommerce->check_order_modify_change()
#3 /home/luwuriveba1620/web/pd-ntnu-test.instawp.xyz/public_html/wp-includes/class-wp-hook.php(308): WSAL_Sensors_WooCommerce->EventChanged()
#4 /home/luwuriveba1620/web/pd-ntnu-test.instawp.xyz/public_html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#5 /home/luwuriveba1620/web/pd-ntnu-test.instawp.xyz/public_html/wp-includes/plugin.php(517): WP_Hook->do_action()
#6 /home/luwuriveba1620/web/pd-ntnu-test.instawp.xyz/public_html/wp-includes/post.php(4717): do_action()
#7 /home/luwuriveba1620/web/pd-ntnu-test.instawp.xyz/public_html/wp-includes/post.php(4819): wp_insert_post()
#8 /home/luwuriveba1620/web/pd-ntnu-test.instawp.xyz/public_html/wp-content/plugins/woocommerce/includes/data-stores/abstract-wc-order-data-store-cpt.php(185): wp_update_post()
#9 /home/luwuriveba1620/web/pd-ntnu-test.instawp.xyz/public_html/wp-content/plugins/woocommerce/includes/data-stores/class-wc-order-data-store-cpt.php(188): Abstract_WC_Order_Data_Store_CPT->update()
#10 /home/luwuriveba1620/web/pd-ntnu-test.instawp.xyz/public_html/wp-content/plugins/woocommerce/includes/class-wc-data-store.php(196): WC_Order_Data_Store_CPT->update()
#11 /home/luwuriveba1620/web/pd-ntnu-test.instawp.xyz/public_html/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-order.php(199): WC_Data_Store->update()
#12 /home/luwuriveba1620/web/pd-ntnu-test.instawp.xyz/public_html/wp-content/plugins/woocommerce/includes/class-wc-order.php(244): WC_Abstract_Order->save()
#13 /home/luwuriveba1620/web/pd-ntnu-test.instawp.xyz/public_html/wp-content/plugins/woocommerce/includes/class-wc-order.php(357): WC_Order->save()
#14 /home/luwuriveba1620/web/pd-ntnu-test.instawp.xyz/public_html/wp-content/plugins/partial-delivery-for-woocommerce/classes/class-partial-delivery-order.php(130): WC_Order->update_status()
#15 /home/luwuriveba1620/web/pd-ntnu-test.instawp.xyz/public_html/wp-content/plugins/partial-delivery-for-woocommerce/classes/class-partial-delivery-ajax.php(56): Delivery_Order->create_delivery_order()
#16 /home/luwuriveba1620/web/pd-ntnu-test.instawp.xyz/public_html/wp-includes/class-wp-hook.php(308): Partial_Delivery_AJAX::wpd_wc_make_delivery()
#17 /home/luwuriveba1620/web/pd-ntnu-test.instawp.xyz/public_html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#18 /home/luwuriveba1620/web/pd-ntnu-test.instawp.xyz/public_html/wp-includes/plugin.php(517): WP_Hook->do_action()
#19 /home/luwuriveba1620/web/pd-ntnu-test.instawp.xyz/public_html/wp-content/plugins/woocommerce/includes/class-wc-ajax.php(94): do_action()
#20 /home/luwuriveba1620/web/pd-ntnu-test.instawp.xyz/public_html/wp-includes/class-wp-hook.php(308): WC_AJAX::do_wc_ajax()
#21 /home/luwuriveba1620/web/pd-ntnu-test.instawp.xyz/public_html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#22 /home/luwuriveba1620/web/pd-ntnu-test.instawp.xyz/public_html/wp-includes/plugin.php(517): WP_Hook->do_action()
#23 /home/luwuriveba1620/web/pd-ntnu-test.instawp.xyz/public_html/wp-includes/template-loader.php(13): do_action()
#24 /home/luwuriveba1620/web/pd-ntnu-test.instawp.xyz/public_html/wp-blog-header.php(19): require_once('...')
#25 /home/luwuriveba1620/web/pd-ntnu-test.instawp.xyz/public_html/index.php(17): require('...')
#26 {main}
thrown in /home/luwuriveba1620/web/pd-ntnu-test.instawp.xyz/public_html/wp-content/plugins/wp-activity-log-for-woocommerce/wp-security-audit-log/custom-sensors/WSAL_Sensors_WooCommerce.php on line 3555
```

**Video:**  https://drive.google.com/file/d/1AQhwO-q0hdaMK_yAs3dIz0sOAdGrFY1Q/view

**Comment by jwjsystem** [comment]
@sdobreff After upgrading the plugin to 4.5, the stack trace of the error is different, so we will need, if possible to provide this guy with a patched version of the extension.

New error.

```
2023-04-19T07:56:00+00:00 CRITICAL Uncaught TypeError: parse_str(): Argument #1 ($string) must be of type string, array given in /home/luwuriveba1620/web/pd-ntnu-test.instawp.xyz/public_html/wp-content/plugins/wp-activity-log-for-woocommerce/wp-security-audit-log/sensors/class-woocommerce-sensor.php:3582
Stack trace:
#0 /home/luwuriveba1620/web/pd-ntnu-test.instawp.xyz/public_html/wp-content/plugins/wp-activity-log-for-woocommerce/wp-security-audit-log/sensors/class-woocommerce-sensor.php(3582): parse_str()
#1 /home/luwuriveba1620/web/pd-ntnu-test.instawp.xyz/public_html/wp-content/plugins/wp-activity-log-for-woocommerce/wp-security-audit-log/sensors/class-woocommerce-sensor.php(3735): WSAL\Plugin_Sensors\WooCommerce_Sensor::event_order_items_quantity_changed()
#2 /home/luwuriveba1620/web/pd-ntnu-test.instawp.xyz/public_html/wp-content/plugins/wp-activity-log-for-woocommerce/wp-security-audit-log/sensors/class-woocommerce-sensor.php(600): WSAL\Plugin_Sensors\WooCommerce_Sensor::check_order_modify_change()
#3 /home/luwuriveba1620/web/pd-ntnu-test.instawp.xyz/public_html/wp-includes/class-wp-hook.php(308): WSAL\Plugin_Sensors\WooCommerce_Sensor::event_changed()
#4 /home/luwuriveba1620/web/pd-ntnu-test.instawp.xyz/public_html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#5 /home/luwuriveba1620/web/pd-ntnu-test.instawp.xyz/public_html/wp-includes/plugin.php(517): WP_Hook->do_action()
#6 /home/luwuriveba1620/web/pd-ntnu-test.instawp.xyz/public_html/wp-includes/post.php(4715): do_action()
#7 /home/luwuriveba1620/web/pd-ntnu-test.instawp.xyz/public_html/wp-includes/post.php(4817): wp_insert_post()
#8 /home/luwuriveba1620/web/pd-ntnu-test.instawp.xyz/public_html/wp-content/plugins/woocommerce/includes/data-stores/abstract-wc-order-data-store-cpt.php(185): wp_update_post()
#9 /home/luwuriveba1620/web/pd-ntnu-test.instawp.xyz/public_html/wp-content/plugins/woocommerce/includes/data-stores/class-wc-order-data-store-cpt.php(188): Abstract_WC_Order_Data_Store_CPT->update()
#10 /home/luwuriveba1620/web/pd-ntnu-test.instawp.xyz/public_html/wp-content/plugins/woocommerce/includes/class-wc-data-store.php(196): WC_Order_Data_Store_CPT->update()
#11 /home/luwuriveba1620/web/pd-ntnu-test.instawp.xyz/public_html/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-order.php(212): WC_Data_Store->update()
#12 /home/luwuriveba1620/web/pd-ntnu-test.instawp.xyz/public_html/wp-content/plugins/woocommerce/includes/class-wc-order.php(244): WC_Abstract_Order->save()
#13 /home/luwuriveba1620/web/pd-ntnu-test.instawp.xyz/public_html/wp-content/plugins/woocommerce/includes/class-wc-order.php(357): WC_Order->save()
#14 /home/luwuriveba1620/web/pd-ntnu-test.instawp.xyz/public_html/wp-content/plugins/partial-delivery-for-woocommerce/classes/class-partial-delivery-order.php(130): WC_Order->update_status()
#15 /home/luwuriveba1620/web/pd-ntnu-test.instawp.xyz/public_html/wp-content/plugins/partial-delivery-for-woocommerce/classes/class-partial-delivery-ajax.php(56): Delivery_Order->create_delivery_order()
#16 /home/luwuriveba1620/web/pd-ntnu-test.instawp.xyz/public_html/wp-includes/class-wp-hook.php(308): Partial_Delivery_AJAX::wpd_wc_make_delivery()
#17 /home/luwuriveba1620/web/pd-ntnu-test.instawp.xyz/public_html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#18 /home/luwuriveba1620/web/pd-ntnu-test.instawp.xyz/public_html/wp-includes/plugin.php(517): WP_Hook->do_action()
#19 /home/luwuriveba1620/web/pd-ntnu-test.instawp.xyz/public_html/wp-content/plugins/woocommerce/includes/class-wc-ajax.php(96): do_action()
#20 /home/luwuriveba1620/web/pd-ntnu-test.instawp.xyz/public_html/wp-includes/class-wp-hook.php(308): WC_AJAX::do_wc_ajax()
#21 /home/luwuriveba1620/web/pd-ntnu-test.instawp.xyz/public_html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#22 /home/luwuriveba1620/web/pd-ntnu-test.instawp.xyz/public_html/wp-includes/plugin.php(517): WP_Hook->do_action()
#23 /home/luwuriveba1620/web/pd-ntnu-test.instawp.xyz/public_html/wp-includes/template-loader.php(13): do_action()
#24 /home/luwuriveba1620/web/pd-ntnu-test.instawp.xyz/public_html/wp-blog-header.php(19): require_once('...')
#25 /home/luwuriveba1620/web/pd-ntnu-test.instawp.xyz/public_html/index.php(17): require('...')
#26 {main}
thrown in /home/luwuriveba1620/web/pd-ntnu-test.instawp.xyz/public_html/wp-content/plugins/wp-activity-log-for-woocommerce/wp-security-audit-log/sensors/class-woocommerce-sensor.php on line 3582
```

**Comment by jwjsystem** [comment]
Sent patch to user and awaiting response.

**Comment by robert81** [comment]
We should open this if the user replies
