### ISSUE TITLE
(forum) Fatal error — sensors/class-woocommerce-sensor.php:3535

### ISSUE THREAD

**Issue by jwjsystem** [wpwhitesecurity/wsal-woocommerce#291]
From the user:

_Buyers also reported seeing “Fatal Error” when they try to check out, ie. they have filled in their billing address, selected payment gateway, and when clicking on the “Place Order” button, it throws a “Fatal Error message”

Some issues:
– some orders in “processing” status suddenly had a lot of a product
– customers report of fatal error at check out_

WordPress 6.0.5
Woocommerce 7.7.2
WP Activity Log (Premium) 4.5.2
WP Activity Log for WooCommerce 1.5.2

```
[20-Jun-2023 03:52:09 UTC] PHP Fatal error:  Uncaught Error: Call to a member function get_status() on bool in /public_html/wp-content/plugins/wp-activity-log-for-woocommerce/wp-security-audit-log/sensors/class-woocommerce-sensor.php:3535
Stack trace:
#0 /public_html/wp-includes/class-wp-hook.php(307): WSAL\Plugin_Sensors\WooCommerce_Sensor::event_order_items_added(105679, Object(WC_Order_Item_Product), 0)
#1 /public_html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(105679, Array)
#2 /public_html/wp-includes/plugin.php(476): WP_Hook->do_action(Array)
#3 /public_html/wp-content/plugins/woocommerce/includes/data-stores/abstract-wc-order-item-type-data-store.php(60): do_action('woocommerce_new...', 105679, Object(WC_Order_Item_Product), 0)
#4 /public_html/wp-content/plugins/woocommerce/includes/class-wc-data-store.php(186): Abstract_WC_Order_Item_Type_Data_Store->create(Object(WC_Order_Item_Product))
#5 /public_html/wp-content/plugins/woocommerce in /public_html/wp-content/plugins/wp-activity-log-for-woocommerce/wp-security-audit-log/sensors/class-woocommerce-sensor.php on line 3535
```

Anything we can do about this or maybe we shall ask for something specific in regards troubleshooting this one? @sdobreff 

More details here: https://wordpress.org/support/topic/fatal-error-sensors-class-woocommerce-sensor-php3535/

**Comment by jwjsystem** [comment]
We have patched this based on all the info gathered from a few users and things are now positive! This was caused by Woo new behavior to create orders just right after user accesses Checkout page. Our sensor did not expect an Order ID to be generated at this stage, and that's what was causing this. 

Closing.
