### ISSUE TITLE
#13764 - Fatal error when placing order

### ISSUE THREAD

**Issue by jwjsystem** [wpwhitesecurity/wsal-woocommerce#292]
We have an user reporting this

_It seems that the latest version is throwing an error in the logs.
_wc_doing_it_wrong(): Order properties should not be accessed directly

The simple reason is that WC does not want a WC_Order to be treated like a regular WP Post such that it's properties are publicly accessible.

We're getting that error when an admin is logged in and places an order via the front end.__

```
[21-Jul-2023 16:22:47 UTC] string(2559) "#0 /var/www/html/wp-content/plugins/woocommerce/includes/legacy/abstract-wc-legacy-order.php(408): wc_doing_it_wrong('post_type', 'Order propertie...', '3.0')
#1 /var/www/html/wp-content/plugins/wp-activity-log-for-woocommerce/wp-security-audit-log/sensors/class-woocommerce-public-sensor.php(146): WC_Abstract_Legacy_Order->__get('post_type')
#2 /var/www/html/wp-content/plugins/wp-activity-log-for-woocommerce/wp-security-audit-log/sensors/class-woocommerce-public-sensor.php(217): WSAL\Plugin_Sensors\WooCommerce_Public_Sensor::get_editor_link(Object(WC_Order))
#3 /var/www/html/wp-includes/class-wp-hook.php(310): WSAL\Plugin_Sensors\WooCommerce_Public_Sensor::event_new_order(6036)
#4 /var/www/html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array)
#5 /var/www/html/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#6 /var/www/html/wp-content/plugins/woocommerce/includes/data-stores/class-wc-order-data-store-cpt.php(111): do_action('woocommerce_new...', 6036, Object(WC_Order))
#7 /var/www/html/wp-content/plugins/woocommerce/includes/class-wc-data-store.php(169): WC_Order_Data_Store_CPT->create(Object(WC_Order))
#8 /var/www/html/wp-content/plugins/woocommerce/includes/abstracts/abstract-wc-order.php(189): WC_Data_Store->create(Object(WC_Order))
#9 /var/www/html/wp-content/plugins/woocommerce/includes/class-wc-order.php(221): WC_Abstract_Order->save()
#10 /var/www/html/wp-content/plugins/woocommerce/includes/class-wc-checkout.php(391): WC_Order->save()
#11 /var/www/html/wp-content/plugins/woocommerce/includes/class-wc-checkout.php(1183): WC_Checkout->create_order(Array)
#12 /var/www/html/wp-content/plugins/woocommerce/includes/class-wc-ajax.php(461): WC_Checkout->process_checkout()
#13 /var/www/html/wp-includes/class-wp-hook.php(308): WC_AJAX::checkout('')
#14 /var/www/html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#15 /var/www/html/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#16 /var/www/html/wp-content/plugins/woocommerce/includes/class-wc-ajax.php(90): do_action('wc_ajax_checkou...')
#17 /var/www/html/wp-includes/class-wp-hook.php(308): WC_AJAX::do_wc_ajax('')
#18 /var/www/html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(false, Array)
#19 /var/www/html/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#20 /var/www/html/wp-includes/template-loader.php(13): do_action('template_redire...')
#21 /var/www/html/wp-blog-header.php(19): require_once('/var/www/html/w...')
#22 /var/www/html/index.php(17): require('/var/www/html/w...')
#23 {main}"
```

I just started troubleshooting - will add more details on the go.

**Comment by jwjsystem** [comment]
Asked for more context/troubleshooting info and/or staging and no response in 1 Month. Closing for now.
