### ISSUE TITLE
#14051 -  Fatal error Dokan Subscription + WC + wsal-woocommerce

### ISSUE THREAD

**Issue by jwjsystem** [wpwhitesecurity/wsal-woocommerce#293]
Upon investigation, it appears that the issue originated from a conflict between the **Dokan Subscription** that our vendors utilise, and your plugin. This conflict caused the subscription to become invalid, consequently taking all the artwork offline.

**WordPress version 6.3
Active theme: Astra (version 4.1.4)
Current plugin: WP Activity Log for WooCommerce (version 1.5.2)
PHP version 8.0.30**

_I have asked them for more information on how to reproduce this and what are the actors involved into this problem - waiting for more details now._ 

```
Error Details
=============
An error of type E_ERROR was caused in line 3535 of the file /srv/htdocs/wp-content/plugins/wp-activity-log-for-woocommerce/wp-security-audit-log/sensors/class-woocommerce-sensor.php. Error message: Uncaught Error: Call to a member function get_status() on bool in /srv/htdocs/wp-content/plugins/wp-activity-log-for-woocommerce/wp-security-audit-log/sensors/class-woocommerce-sensor.php:3535
Stack trace:
#0 /wordpress/core/6.3/wp-includes/class-wp-hook.php(310): WSAL\Plugin_Sensors\WooCommerce_Sensor::event_order_items_added(1587, Object(WC_Order_Item_Product), 0)
#1 /wordpress/core/6.3/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters(NULL, Array)
#2 /wordpress/core/6.3/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#3 /wordpress/plugins/woocommerce/8.0.2/includes/data-stores/abstract-wc-order-item-type-data-store.php(60): do_action('woocommerce_new...', 1587, Object(WC_Order_Item_Product), 0)
#4 /wordpress/plugins/woocommerce/8.0.2/includes/class-wc-data-store.php(186): Abstract_WC_Order_Item_Type_Data_Store->create(Object(WC_Order_Item_Product))
#5 /wordpress/plugins/woocommerce/8.0.2/includes/abstracts/abstract-wc-data.php(228): WC_Data_Store->create(Object(WC_Order_Item_Product))
#6 /wordpress/plugins/woocommerce/8.0.2/includes/abstracts/abstract-wc-order.php(1558): WC_Data->save()
#7 /srv/htdocs/wp-content/plugins/dokan-pro/modules/subscription/includes/admin/admin.php(1176): WC_Abstract_Order->add_product(Object(WC_Product_Product_pack))
#8 /wordpress/core/6.3/wp-includes/class-wp-hook.php(310): DPS_Admin::save_meta_fields(234905316)
#9 /wordpress/core/6.3/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters(NULL, Array)
#10 /wordpress/core/6.3/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#11 /srv/htdocs/wp-content/plugins/dokan-lite/includes/Admin/UserProfile.php(592): do_action('dokan_process_s...', 234905316)
#12 /wordpress/core/6.3/wp-includes/class-wp-hook.php(310): WeDevs\Dokan\Admin\UserProfile->save_meta_fields(234905316)
#13 /wordpress/core/6.3/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters(NULL, Array)
#14 /wordpress/core/6.3/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#15 /wordpress/core/6.3/wp-admin/user-edit.php(157): do_action('edit_user_profi...', 234905316)
#16 {main}
thrown
```

**Comment by jwjsystem** [comment]
Sent patch to user. Waiting for confirmation

**Comment by jwjsystem** [comment]
Closing this one - havent heared back and would consider everything turned out positive!
